version: '3.3'

services:
  vue-app:
    build: .
    command: http-server dist/ -p 8080 --cors
    volumes:
      - .:/app
    ports:
      - '8080:8080'
    networks:
      - backend-net

networks:
  backend-net:
    external: true
