version: '3.3'

services:
  vue-app:
    build: .
    command: http-server dist/ -p 8000
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    networks:
      - backend-net

networks:
  backend-net:
    external: true
